# Generated by Django 4.0.6 on 2022-07-26 09:40

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_abi_alv_amgn_amzn_ba_bats_bhp_bp_c_csco_cvx_dd_dis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PFYH_600000',
            fields=[
                ('Date', models.CharField(max_length=10, primary_key=sqlalchemy.sql.expression.true, serialize=False)),
                ('Open', models.FloatField(null=sqlalchemy.sql.expression.true)),
                ('Close', models.FloatField(null=sqlalchemy.sql.expression.true)),
                ('High', models.FloatField(null=sqlalchemy.sql.expression.true)),
                ('Low', models.FloatField(null=sqlalchemy.sql.expression.true)),
                ('Volume', models.FloatField(null=sqlalchemy.sql.expression.true)),
                ('Code', models.IntegerField(null=sqlalchemy.sql.expression.true)),
            ],
        ),
    ]
